[discord]
token = "TOKEN"
application_id = "APPLICATION_ID"
#
# Use "guild" while developing.
# When running in production, use "global"
command_registration_type = "guild"
development_guild_id = "903333333973491842"

[database]
type = "mysql"
# Only when type = "sqlite"
# file = "data.sqlite"
host = "localhost"
port = 3306
username = "root"
password = ""
database = "prisy"
synchronize = true
logging = false

[guild_defaults]
prefix = "-"
language = "en"