[discord]
token = "TOKEN"

[database]
type = "mysql"
# Only when type = "sqlite"
# file = "data.sqlite"
host = "localhost"
port = 3306
username = "root"
password = ""
database = "prisy"
synchronize = true
logging = false

[guild_defaults]
prefix = "-"
language = "en"